---
- name: Build and push a container image for hosting the RPM OSTree image 
  become: true
  hosts: all

  tasks:  
    - name: Ensure required packages are installed
      ansible.builtin.dnf: 
        name: 
          - podman
          - pip

    - name: Install python requirements
      ansible.builtin.pip:
        name: kubernetes

    - name: Login into registry.redhat.io
      containers.podman.podman_login:
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        registry: registry.redhat.io

    - name: Copy Containerfile to build directory
      ansible.builtin.copy:
        src: files/Containerfile
        dest: "/var/www/html/{{ image_name }}/Containerfile"

    - name: Dump the lock file
      ansible.builtin.file:
        path: "/var/www/html/{{ image_name }}/repo/.lock"
        state: absent

    - name: Build container
      containers.podman.podman_image:
        name: "{{ image_name }}:{{ image_version }}"
        path: "/var/www/html/{{ image_name }}"
        build:
          format: oci

  post_tasks:
    - debug:
        msg: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_USERNAME') }}"
    - debug:
        msg: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_API_KEY') }}"
    - debug:
        msg: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_HOST') }}"    

    - name: Read integrated registry information
      redhat.openshift.openshift_registry_info:
        username: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_API_KEY') }}"
      register: registry

    - name: Login into Openshift Internal registry
      containers.podman.podman_login:
        username: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_API_KEY') }}"
        registry: "{{ registry.internal_hostname }}"