---
- name: Build and push a container image for hosting the RPM OSTree image 
  become: true
  hosts: all

  tasks:  
    - name: Ensure required packages are installed
      ansible.builtin.dnf: 
        name: 
          - podman

    - name: Get list of all created images
      infra.osbuild.get_all_finished_images:
      register: all_images

    - debug:
        var: all_images

    - name: Get newest image by job_created
      set_fact:
        newest_image: "{{ all_images.result.finished | sort(attribute='job_created') | last }}"

    - name: Show newest image
      debug:
        var: newest_image

    - name: Build container
      containers.podman.podman_load:
        input: "/var/www/html/{{ image_name }}/{{ newest_image.id }}-container.tar"
      register:
        podman_image

    - debug:
        var: podman_image        

    - name: Login into quay.io
      containers.podman.podman_login:
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        registry: quay.io

    # - name: Push the into Openshift Internal registry
    #   containers.podman.podman_image:
    #     name: "{{ image_name }}:{{ image_version }}"
    #     push: true
    #     push_args:
    #        dest: "{{ registry_url }}"